apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web-img
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web-img
    spec:
      containers:
      - name: app-with-argocd-img
        image: yhy0009/app-with-argocd-img:80630737171739cd9609ef1d5b3029a0f8b5290f
